export const userFormValidationConstants = {
  MIN_NAME_LENGTH: 2,
  MAX_NAME_LENGTH: 30,
  MIN_SURNAME_LENGTH: 2,
  MAX_SURNAME_LENGTH: 30,
  MIN_PHONE_NUMBER_LENGTH: 9,
  MAX_PHONE_NUMBER_LENGTH: 15,
  PESEL_LENGTH: 11,
  MIN_PASSWORD_LENGTH: 6,
  MAX_PASSWORD_LENGTH: 30,
};
